import React, { useState } from 'react';
import { X, Check, Copy, Share2, Plus, ShoppingBag, CheckCircle2, Refrigerator } from 'lucide-react';
import { DailyMenu } from '../types/meal';

interface ShoppingListModalProps {
  menu: DailyMenu;
  onClose: () => void;
}

export const ShoppingListModal: React.FC<ShoppingListModalProps> = ({
  menu,
  onClose,
}) => {
  const [checkedItems, setCheckedItems] = useState<Record<string, boolean>>({});
  const [showHaveAtHome, setShowHaveAtHome] = useState(false);
  const [newItemName, setNewItemName] = useState('');
  const [newItemQty, setNewItemQty] = useState('');
  const [customItems, setCustomItems] = useState<{ name: string; quantity: string; checked: boolean }[]>([]);
  const [copiedNotification, setCopiedNotification] = useState(false);

  const toggleItem = (key: string) => {
    setCheckedItems(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const addCustomItem = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newItemName.trim()) return;
    setCustomItems(prev => [...prev, { name: newItemName.trim(), quantity: newItemQty.trim() || '1 item', checked: false }]);
    setNewItemName('');
    setNewItemQty('');
  };

  const copyForWhatsApp = () => {
    let text = `🛒 *Grocery Shopping List - ${menu.title}*\n_For ${menu.servings} people_\n\n`;

    menu.shoppingList?.forEach(cat => {
      const neededItems = cat.items.filter(item => showHaveAtHome || !item.haveAtHome);
      if (neededItems.length > 0) {
        text += `*${cat.category}*:\n`;
        neededItems.forEach(item => {
          const isDone = checkedItems[`${cat.category}-${item.name}`];
          text += `  ${isDone ? '✓ ' : '• '} ${item.name} — ${item.quantity}\n`;
        });
        text += '\n';
      }
    });

    if (customItems.length > 0) {
      text += `*Custom Added Items*:\n`;
      customItems.forEach(item => {
        text += `  • ${item.name} (${item.quantity})\n`;
      });
      text += '\n';
    }

    text += `_Generated by Enna Samayal? Meal Planner_`;

    navigator.clipboard.writeText(text);
    setCopiedNotification(true);
    setTimeout(() => setCopiedNotification(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/60 backdrop-blur-xs animate-in fade-in duration-200">
      <div 
        className="relative w-full max-w-lg max-h-[90vh] bg-[#FAF7F2] rounded-3xl shadow-2xl border border-[#E8DFC8] flex flex-col overflow-hidden text-[#2D241E]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="bg-gradient-to-r from-[#8B6F20] to-[#B89230] text-white p-5 relative flex-shrink-0">
          <button
            onClick={onClose}
            className="absolute top-4 right-4 p-2 rounded-full bg-white/10 hover:bg-white/20 text-white transition-colors"
            aria-label="Close"
          >
            <X className="w-5 h-5" />
          </button>

          <div className="flex items-center space-x-2 text-amber-100 text-xs font-semibold uppercase tracking-wider mb-1">
            <ShoppingBag className="w-4 h-4" />
            <span>Consolidated Groceries</span>
          </div>

          <h2 className="text-2xl font-bold font-display text-amber-50">
            Shopping List
          </h2>
          <p className="text-white/80 text-xs mt-1">
            Ingredients consolidated for {menu.servings} people from today's menu
          </p>
        </div>

        {/* Filter and WhatsApp Share Action Bar */}
        <div className="bg-[#F3ECE2] px-5 py-3 border-b border-[#E2D5C3] flex items-center justify-between gap-2 text-xs flex-shrink-0">
          <label className="flex items-center space-x-2 text-[#5A4B3E] font-medium cursor-pointer">
            <input
              type="checkbox"
              checked={showHaveAtHome}
              onChange={(e) => setShowHaveAtHome(e.target.checked)}
              className="rounded border-[#C8B8A6] text-[#A84B2C] focus:ring-[#A84B2C]"
            />
            <span>Show items already in pantry</span>
          </label>

          <button
            onClick={copyForWhatsApp}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded-xl bg-emerald-700 hover:bg-emerald-800 text-white font-bold transition-all shadow-xs flex-shrink-0 cursor-pointer"
          >
            {copiedNotification ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-200" />
                <span>Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy for WhatsApp</span>
              </>
            )}
          </button>
        </div>

        {/* Categories and items */}
        <div className="p-5 overflow-y-auto space-y-5 flex-1 text-sm">
          {menu.shoppingList && menu.shoppingList.length > 0 ? (
            menu.shoppingList.map((cat, cIdx) => {
              const itemsToRender = cat.items.filter(item => showHaveAtHome || !item.haveAtHome);
              if (itemsToRender.length === 0) return null;

              return (
                <div key={cIdx} className="space-y-2">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-[#7A6A5D] flex items-center">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#A84B2C] mr-2" />
                    {cat.category}
                  </h3>

                  <div className="space-y-1.5">
                    {itemsToRender.map((item, iIdx) => {
                      const key = `${cat.category}-${item.name}`;
                      const isChecked = !!checkedItems[key];

                      return (
                        <div
                          key={iIdx}
                          onClick={() => toggleItem(key)}
                          className={`p-2.5 rounded-xl border flex items-center justify-between transition-all cursor-pointer ${
                            isChecked
                              ? 'bg-[#EAE4DC]/50 border-transparent text-[#9C8C7F] line-through'
                              : item.haveAtHome
                              ? 'bg-amber-50/50 border-amber-200/50 text-[#6B5E52]'
                              : 'bg-white border-[#E8DFC8] text-[#2D241E] shadow-2xs hover:border-[#A84B2C]/40'
                          }`}
                        >
                          <div className="flex items-center space-x-3">
                            <div className={`w-5 h-5 rounded-md flex items-center justify-center border transition-all ${
                              isChecked
                                ? 'bg-emerald-600 border-emerald-600 text-white'
                                : 'border-[#C8B8A6] bg-white'
                            }`}>
                              {isChecked && <Check className="w-3.5 h-3.5 stroke-[3]" />}
                            </div>
                            <span className="font-medium text-xs sm:text-sm">{item.name}</span>
                          </div>

                          <div className="flex items-center space-x-2">
                            {item.haveAtHome && (
                              <span className="text-[10px] bg-emerald-100 text-emerald-800 px-1.5 py-0.5 rounded font-bold">
                                Have at home
                              </span>
                            )}
                            <span className="text-xs font-bold text-[#A84B2C] bg-[#F3ECE2] px-2 py-0.5 rounded-md">
                              {item.quantity}
                            </span>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              );
            })
          ) : (
            <div className="text-center py-8 text-[#7A6A5D] text-xs">
              No ingredients required or all items already in pantry.
            </div>
          )}

          {/* Custom user-added items */}
          {customItems.length > 0 && (
            <div className="space-y-2 pt-2 border-t border-[#E8DFC8]">
              <h3 className="text-xs font-bold uppercase tracking-wider text-[#7A6A5D]">
                Custom Added Items
              </h3>
              <div className="space-y-1.5">
                {customItems.map((item, idx) => (
                  <div
                    key={idx}
                    className="p-2.5 rounded-xl border bg-white border-[#E8DFC8] flex items-center justify-between text-xs"
                  >
                    <span className="font-medium text-[#2D241E]">{item.name}</span>
                    <span className="font-bold text-[#A84B2C] bg-[#F3ECE2] px-2 py-0.5 rounded-md">
                      {item.quantity}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Quick Add Custom Item Form */}
          <form onSubmit={addCustomItem} className="pt-2 border-t border-[#E8DFC8] space-y-2">
            <span className="text-[11px] font-bold text-[#7A6A5D] block">
              + Add extra grocery item (e.g. Milk, Ghee, Spices)
            </span>
            <div className="flex items-center gap-2">
              <input
                type="text"
                value={newItemName}
                onChange={(e) => setNewItemName(e.target.value)}
                placeholder="Item name (e.g., Hing, Curry leaves)"
                className="flex-1 bg-white border border-[#E2D5C3] rounded-xl px-3 py-2 text-xs text-[#2D241E] focus:outline-none focus:border-[#A84B2C]"
              />
              <input
                type="text"
                value={newItemQty}
                onChange={(e) => setNewItemQty(e.target.value)}
                placeholder="Qty (e.g., 100g)"
                className="w-24 bg-white border border-[#E2D5C3] rounded-xl px-3 py-2 text-xs text-[#2D241E] focus:outline-none focus:border-[#A84B2C]"
              />
              <button
                type="submit"
                className="p-2 rounded-xl bg-[#A84B2C] hover:bg-[#8F3C20] text-white transition-colors cursor-pointer"
              >
                <Plus className="w-4 h-4" />
              </button>
            </div>
          </form>
        </div>

        {/* Footer */}
        <div className="p-4 bg-[#F3ECE2] border-t border-[#E2D5C3] flex items-center justify-between">
          <span className="text-xs text-[#7A6A5D]">
            {Object.values(checkedItems).filter(Boolean).length} items checked off
          </span>
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-[#2D241E] hover:bg-[#40332B] text-white text-xs font-bold transition-colors cursor-pointer"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
};
